### ISSUE TITLE
FAIR Code Checklist versioning and links

### ISSUE THREAD

**Issue by imartorelli** [ubvu/codechecklist#1]
I have a few questions regarding the FAIR code checklist [flyer version](https://github.com/ubvu/codechecklist/blob/main/Flyer_RSM.pdf):

-  [ ] **How is the checklist linked to the FAIR software principles?**
  - It would be helpful to explain or give some keywords on why each point is usefulFor example, version control could mention backup and/or collaboration, etc.. 
  - Versioning goes well with Findability and adding a README file makes the code more interoperable and reusable..

- [ ]  **Checklist 1 on version control**:
   - It is great that you encourage version control, however this section seems to mix versioning with sensitivity items, software with data aspects which can be confusing to the reseacher. It is about FAIR software principles but I lose completely the main focus on version control here. It seems like I should contact RMD support if I have concerns about data sensitivity rather than on version control. Also data and code can be FAIR but not necessarily open. Perhaps I would put the sensitivity concern on a note and/or other point after the version control aspect. For example: *Note* - if your code contains sensitive data, then consult with RDM support team before making it public... 
   - The Yes and Maybe points provide the same type of information and it confuses me why I should contact RDM if my answer is Yes. If this first statement is about versioning, then I would suggest to put something like: 
      1. Yes: I am using version control (for example on GitHub) and my code is publicly available
      2. No: I am not yet using version control - create a new repo on a version control ...
      3. I do not know: Contact RDM ...

-  [ ] **Reference with urls**
   - I really like that tools and resources listed and linked on this page. I would suggest to extend them. For example when mentioning ORCID, use [Create an ORCID](https://libguides.vu.nl/orcid/register), like you have used for CITATION.cff 
   - Same for [Research Software Directory](https://research-software-directory.org)
 
great work and thanks for considering these items :)
